backend:
  name: github
  repo: Gojodzojo/maitri-bytom-website
  branch: main

media_folder: "public/img" # Folder where user uploaded files should go
public_folder: "/img"

collections: # A list of collections the CMS should be able to edit
  - name: "strony_gornego_paska" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Strony górnego paska" # Used in the UI, ie.: "New Post"
    folder: "src/content/header_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Pozycja na pasku", name: "header_position", widget: "number", min: 1}
      - {label: "Treść", name: "body", widget: "markdown"}
      - {label: "Galeria zdjęć", name: "image_gallery", widget: "list", required: false, summary: '{{fields.image}}', collapsed: true, label_singular: "image", field: {label: "Zdjęcie", name: image, widget: image}}

  - name: "aktualnosci"
    label: "Aktualności"
    folder: "src/content/news" 
    create: true 
    fields: 
      - {label: "Zdjęcie artykułu", name: "image", widget: "image", allow_multiple: false}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data publikacji", name: "date", widget: "datetime"}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Tagi oddzielone przecinkiem", name: "tags", widget: "list"}
      - {label: "Treść", name: "body", widget: "markdown"}
      - {label: "Galeria zdjęć", name: "image_gallery", widget: "list", required: false, summary: '{{fields.image}}', collapsed: true, label_singular: "image", field: {label: "Zdjęcie", name: image, widget: image}}

  - name: "sekcje_stopki"
    label: "Sekcje stopki"
    folder: "src/content/footer_sections"
    create: true 
    fields: 
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Pozycja w stopce", name: "footer_position", widget: "number", min: 1}
      - {label: "Treść", name: "body", widget: "markdown"}

  - name: "strona_glowna"
    label: "Strona główna"
    files: 
    - file: "src/content/index.md"  
      name: "strona_glowna"
      label: "Strona główna"
      fields: 
        - {label: "Tytuł", name: "title", widget: "string"}
        - {label: "Treść", name: "body", widget: "markdown"}