locale: 'pl'
logo_url: https://raw.githubusercontent.com/Gojodzojo/maitri-bytom-website/main/page/public/Logo-Maitri.png

backend:
  name: github
  repo: Gojodzojo/maitri-bytom-website
  branch: main

media_folder: "page/public/img" # Folder where user uploaded files should go
public_folder: "/img"

collections: # A list of collections the CMS should be able to edit
  - name: "strony_gornego_paska" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Strony górnego paska" # Used in the UI, ie.: "New Post"
    folder: "page/src/markdown/header_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Pozycja na pasku", name: "position", widget: "number", min: 1}
      - {label: "Czy szkic? (nie będzie widoczny na stronie)", name: "draft", widget: "boolean", default: true }
      - {label: "Treść", name: "body", widget: "markdown", editor_components: ["zoomable-img", "image-gallery"]}

  - name: "aktualnosci"
    label: "Aktualności"
    folder: "page/src/markdown/news" 
    create: true 
    fields: 
      - {label: "Zdjęcie artykułu", name: "image", widget: "image", allow_multiple: false}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data publikacji", name: "date", widget: "datetime", date_format: "DD-MM-YYYY", time_format: false}
      - {label: "Autor", name: "author", widget: "string"}
      - {label: "Czy szkic? (nie będzie widoczny na stronie)", name: "draft", widget: "boolean", default: true }
      - {label: "Tagi oddzielone przecinkiem", name: "tags", widget: "list"}
      - {label: "Treść", name: "body", widget: "markdown", editor_components: ["zoomable-img", "image-gallery"]}

  - name: "sekcje_stopki"
    label: "Sekcje stopki"
    folder: "page/src/markdown/footer_sections"
    create: true 
    fields: 
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Pozycja w stopce", name: "position", widget: "number", min: 1}
      - {label: "Czy szkic? (nie będzie widoczny na stronie)", name: "draft", widget: "boolean", default: true }
      - {label: "Treść", name: "body", widget: "markdown", editor_components: []}

  - name: "strona_glowna"
    label: "Strona główna"
    files: 
    - file: "page/src/markdown/index.md"  
      name: "strona_glowna"
      label: "Strona główna"
      fields: 
        - {label: "Galeria zdjęć", name: "image_gallery", widget: "list", required: false, summary: '{{fields.image}}', collapsed: true, label_singular: "zdjęcie", field: {label: "Zdjęcie", name: image, widget: image}}
        - {label: "Tytuł", name: "title", widget: "string"}
        - {label: "Treść", name: "body", widget: "markdown", editor_components: ["zoomable-img", "image-gallery"]}
  
  - name: "instrukcja"
    label: "Instrukcja"
    files: 
    - file: "page/src/markdown/instruction.md"  
      name: "instrukcja"
      label: "Instrukcja"
      fields: 
        - {label: "Tytuł", name: "title", widget: "string"}
        - {label: "Treść", name: "body", widget: "markdown", editor_components: ["zoomable-img", "image-gallery"]}