name: deploy

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install and build Astro
        run: |
          npm ci
          npm run build

      - name: Install lftp
        run: sudo apt install lftp

      - name: Deploy
        run: cd dist && lftp -u "${{ secrets.FTP_USERNAME }}","${{ secrets.FTP_PASSWORD }}" "${{ secrets.FTP_HOSTNAME }}" -e "mirror -c -e -R -x .ftpquota; exit"
